version: '3.9'
services:
  api:
    build: .
    # image: 'cloud image name when available'
    command: npm run dev
    env_file:
      - .env
    volumes:
      - .:/usr/cprh/api
    ports:
      - "10000:10000"
    container_name: cprh-api
    # links:
    #   - mongo-db
