version: '3.9'
services:
  webapp:
    build: .
    command: npm run start
    env_file:
      - .env
    volumes:
      # allows to make changes to the project from local development, will be picked up by project inside Docker
      - .:/usr/app/ 
      - /usr/app/node_modules
    ports:
      - "8000:8000"