name: docker reusable workflow
on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish_docker_image:
    # needs: build_node_app
    name: build docker image and publish it to dockerhub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-user: [ridao]
        app-name: [cprh-app]
        tag: [latest]
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: create env file for building
        # warning: all env vars must be added here as well. print for sanity
        run: |
          touch .env
          echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
          echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
          echo LOG_LEVEL=info >> .env
          echo NODE_ENV=production >> .env
          echo PORT=10000 >> .env
          cat .env

      - name: build docker image
        run: docker build . -t ${{ matrix.docker-user }}/${{ matrix.app-name }}:${{ matrix.tag }}
      - name: login to dockerhub
        run: docker login -u ${{ matrix.docker-user }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image to dockerhub
        run: docker push ${{ matrix.docker-user }}/${{ matrix.app-name }}:${{ matrix.tag }}