# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create env file
      run: |
        touch .env
        echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
        echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
        echo LOG_LEVEL=info >> .env
        echo NODE_ENV=production >> .env
        echo PORT=8000 >> .env
        cat .env
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
