# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DEV Node CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build, test & docker for development
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        docker-user: [ridao]
        app-name: [cprh]
    # Docker container params
    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      LOG_LEVEL: info
      NODE_ENV: development # for the tests
      PORT: 8000
    steps:
    # Setup container
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Create env file for env vars
    - name: Create env file
      run: |
        touch .env
        echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
        echo CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} >> .env
        echo LOG_LEVEL=info >> .env
        echo NODE_ENV=development >> .env
        echo PORT=8000 >> .env
        cat .env
    - name: Run npm ci to install dependencies    
      run: npm ci

    # Run tests
    - name: Run tests
      run: npm test
    
    # Create docker image
    - name: Create docker image
      run: docker build . -t ${{ matrix.docker-user }}/${{ matrix.app-name }}:dev

    # Publish image to dockerhub
    - name: Login to dockerhub
      run: docker login -u ${{ matrix.docker-user }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push image to dockerhub
      run: docker push ${{ matrix.docker-user }}/cprh:dev
